"""Bidirectional conversion between agent-loop's provider-agnostic message /
tool-schema types and LangChain's `BaseMessage` / `StructuredTool` types.

Used exclusively by `LangChainTransport` (`langchain_transport.py`) — no
other module should need to reach into LangChain message shapes directly,
keeping the rest of the adapter layer decoupled from LangChain's wire
format the same way `AnthropicTransport`/`OpenAITransport` keep their SDKs
from leaking past `transport/`.

Tool-name note: `ToolSchema.name` values reaching this module are already
LLM-safe (`BoundMethodTool.name` from agent_loop_lib joins
`{toolset}__{tool_name}` with double-underscore separator for connector
tools) — unlike PipesHub's legacy LangGraph path, no dot-to-underscore
sanitization is needed here.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import TYPE_CHECKING, Any, Literal

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage
from langchain_core.messages import SystemMessage as LCSystemMessage
from langchain_core.messages import ToolMessage as LCToolMessage
from pydantic import BaseModel, Field, create_model

from app.agent_loop_lib.core.messages import (
    MALFORMED_TOOL_CALL_ARGS_KEY,
    MALFORMED_TOOL_CALL_ERROR_KEY,
    AssistantMessage,
    ImagePart,
    ImageSource,
    MessageRole,
    SystemMessage,
    TextPart,
    ThinkingPart,
    ToolCall,
    ToolMessage,
    UserMessage,
)
from app.agent_loop_lib.core.responses import TokenUsage

if TYPE_CHECKING:
    from app.agent_loop_lib.core.messages import Message, Part
    from app.agent_loop_lib.core.tool_schema import ToolSchema

# response_metadata keys different LangChain chat model integrations use to
# signal the completion was cut off at the output-token cap.
_TRUNCATION_FINISH_REASONS = {"length", "max_tokens"}

# OpenAI's Responses API (used for gpt-5.x reasoning models, see
# `aimodels._reasoning_effort_kwargs`) never populates `finish_reason` — it
# reports a cut-off answer as `status="incomplete"` with the cause under
# `incomplete_details.reason`. Only the output-token cause counts as
# truncation; `content_filter` is a different stop the recovery path in
# `agent/__init__.py` must not treat as "continue where you left off".
_TRUNCATION_INCOMPLETE_REASONS = {"max_output_tokens", "max_tokens"}

# OpenAI/Azure enforce max 64 characters on `tool_calls[].id` and on the
# matching `tool_call_id` in a ToolMessage. IDs originate from three
# sources: (1) the model's own response (`call_abc123...`), (2) persisted
# conversation history replayed via `_convert_conversation_turn` / the
# `parts` transcript, (3) synthetic IDs generated by our own code
# (`history_0`, `tool_0`, ...). Source (1) is normally <=64 already but
# there is no contractual guarantee from every provider's model version;
# source (2) can carry IDs from other providers (Anthropic uses longer
# ones). A single over-length ID 400s the entire request. Truncation
# preserves a recognizable prefix + a hash suffix so the tool-call and its
# result still match after shortening, and two different long IDs don't
# accidentally collide.
_MAX_TOOL_CALL_ID_LENGTH = 64


def _clamp_tool_call_id(raw_id: str) -> str:
    if len(raw_id) <= _MAX_TOOL_CALL_ID_LENGTH:
        return raw_id
    digest = hashlib.sha256(raw_id.encode()).hexdigest()[:16]
    prefix_len = _MAX_TOOL_CALL_ID_LENGTH - 1 - len(digest)  # 1 for the `-`
    return f"{raw_id[:prefix_len]}-{digest}"


def _image_part_to_block(part: ImagePart) -> dict[str, Any]:
    source = part.source
    if source.type == "url":
        url = source.data
    else:
        media_type = source.media_type or "image/png"
        url = f"data:{media_type};base64,{source.data}"
    return {"type": "image_url", "image_url": {"url": url}}


def _part_to_block(part: Part) -> dict[str, Any]:
    if isinstance(part, TextPart):
        return {"type": "text", "text": part.text}
    if isinstance(part, ImagePart):
        return _image_part_to_block(part)
    if isinstance(part, ThinkingPart):
        # Thinking content should never be replayed as ordinary text to a
        # provider — same rule AnthropicTransport follows internally — but a
        # user-authored ThinkingPart is not a real scenario, so a plain-text
        # fallback here is defensive rather than load-bearing.
        return {"type": "text", "text": part.thinking}
    return {"type": "text", "text": str(part)}


def _langchain_block_to_part(block: dict[str, Any]) -> Part | None:
    block_type = block.get("type")
    if block_type == "text":
        text = block.get("text", "")
        return TextPart(text=text) if text else None
    if block_type == "image_url":
        image_url = block.get("image_url") or {}
        url = image_url.get("url", "") if isinstance(image_url, dict) else str(image_url)
        if url:
            return ImagePart(source=ImageSource(type="url", data=url))
    return None


def convert_message_from_langchain(message: BaseMessage) -> Message:
    """Convert one LangChain message into agent-loop's message model."""
    if isinstance(message, LCSystemMessage):
        content = message.content
        return SystemMessage(content=content if isinstance(content, str) else str(content))

    if isinstance(message, HumanMessage):
        content = message.content
        if isinstance(content, str):
            return UserMessage(content=content)
        if isinstance(content, list):
            parts: list[Part] = []
            for block in content:
                if isinstance(block, dict):
                    part = _langchain_block_to_part(block)
                    if part is not None:
                        parts.append(part)
                elif isinstance(block, str) and block:
                    parts.append(TextPart(text=block))
            return UserMessage(content=parts or "")
        return UserMessage(content=str(content))

    if isinstance(message, AIMessage):
        text = message.content if isinstance(message.content, str) else str(message.content)
        tool_calls = [convert_tool_call_from_langchain(c) for c in (message.tool_calls or [])]
        return AssistantMessage(content=text, tool_calls=tool_calls or None)

    if isinstance(message, LCToolMessage):
        content = message.content
        if isinstance(content, list):
            parts: list[Part] = []
            for block in content:
                if isinstance(block, dict):
                    part = _langchain_block_to_part(block)
                    if part is not None:
                        parts.append(part)
                elif isinstance(block, str) and block:
                    parts.append(TextPart(text=block))
            return ToolMessage(
                content=parts or "",
                tool_call_id=message.tool_call_id,
                is_error=getattr(message, "status", None) == "error",
            )
        return ToolMessage(
            content=content if isinstance(content, str) else str(content),
            tool_call_id=message.tool_call_id,
            is_error=getattr(message, "status", None) == "error",
        )

    raise ValueError(f"Unsupported LangChain message type: {type(message)!r}")


def convert_messages_from_langchain(messages: list[BaseMessage]) -> list[Message]:
    return [convert_message_from_langchain(m) for m in messages]


def convert_message_to_langchain(
    message: Message, *, strip_tool_images: bool = False,
) -> BaseMessage:
    """Convert one agent-loop `Message` to its LangChain equivalent.

    `strip_tool_images`: True for chat models whose provider does not
    accept image content in a tool-result message (Ollama's `/api/chat`,
    OpenAI-family models on Chat Completions — see
    `LangChainTransport._supports_multipart_tool_result`). Providers that
    do accept multipart tool results (Anthropic, Gemini, Bedrock, ...) keep
    images inline here; the stripped images are recovered from
    `context.tool_state["pending_tool_images"]` and re-injected into a
    `UserMessage` by the `shape_retrieved_image_injection` PRE_MODEL
    fallback hook (`attachment_resolver.py`).
    """
    if message.role == MessageRole.SYSTEM:
        return LCSystemMessage(content=message.content)

    if message.role == MessageRole.USER:
        content = message.content
        if isinstance(content, str):
            return HumanMessage(content=content)
        return HumanMessage(content=[_part_to_block(p) for p in content])

    if message.role == MessageRole.ASSISTANT:
        tool_calls = [
            {"name": tc.name, "args": tc.arguments, "id": _clamp_tool_call_id(tc.id)}
            for tc in (message.tool_calls or [])
        ]
        # Replaying thinking content back to the provider on the next turn
        # is neither required nor universally supported — only the text is
        # resent, matching AnthropicTransport's own outgoing formatting.
        return AIMessage(content=message.text, tool_calls=tool_calls)

    if message.role == MessageRole.TOOL:
        content = message.content
        if isinstance(content, list):
            if strip_tool_images:
                serialized_content = message.text + message.step_footer
                return LCToolMessage(
                    content=serialized_content,
                    tool_call_id=_clamp_tool_call_id(message.tool_call_id or ""),
                    status="error" if message.is_error else "success",
                )
            blocks = [_part_to_block(p) for p in content]
            if message.step_footer:
                blocks.append({"type": "text", "text": message.step_footer})
            return LCToolMessage(
                content=blocks,
                tool_call_id=_clamp_tool_call_id(message.tool_call_id or ""),
                status="error" if message.is_error else "success",
            )
        serialized_content = content + message.step_footer
        return LCToolMessage(
            content=serialized_content,
            tool_call_id=_clamp_tool_call_id(message.tool_call_id or ""),
            status="error" if message.is_error else "success",
        )

    raise ValueError(f"Unsupported agent-loop message role: {message.role!r}")


# Prefix for the user message `relocate_tool_images` parks tool-sourced images
# under, so the model can tell them apart from what the user itself attached.
_RELOCATED_IMAGES_PREFIX = "Images returned by the tool results above:"


def convert_messages_to_langchain(
    messages: list[Message],
    system: str | None = None,
    *,
    strip_tool_images: bool = False,
    relocate_tool_images: bool = False,
) -> list[BaseMessage]:
    """Convert a full agent-loop message list, prepending `system` as a
    LangChain `SystemMessage` when provided (mirrors `LLMTransport.complete`'s
    contract: `system` arrives as a separate kwarg, not inside `messages`).

    `relocate_tool_images`: strip images out of tool results (as
    `strip_tool_images` does) but re-attach them to a trailing `HumanMessage`
    instead of dropping them. Used by `LangChainTransport`'s runtime recovery
    from a provider that rejects images in a tool-result message
    (`is_tool_result_image_conflict`) — that path has no
    `shape_retrieved_image_injection` hook registered to recover the images
    from `pending_tool_images`, since the factory registers that hook only for
    providers `_supports_multipart_tool_result` rejects up front, so without
    re-attaching them here the retry would answer about images it never saw.
    """
    converted = [
        convert_message_to_langchain(
            m, strip_tool_images=strip_tool_images or relocate_tool_images,
        )
        for m in messages
    ]
    if relocate_tool_images:
        blocks = [
            _image_part_to_block(part)
            for m in messages
            if m.role == MessageRole.TOOL and isinstance(m.content, list)
            for part in m.content
            if isinstance(part, ImagePart)
        ]
        if blocks:
            converted.append(HumanMessage(
                content=[{"type": "text", "text": _RELOCATED_IMAGES_PREFIX}, *blocks],
            ))
    if system:
        return [LCSystemMessage(content=system), *converted]
    return converted


def has_tool_result_images(messages: list[Message]) -> bool:
    """Whether any tool result carries an `ImagePart` — i.e. whether
    `relocate_tool_images` has anything to move."""
    return any(
        m.role == MessageRole.TOOL
        and isinstance(m.content, list)
        and any(isinstance(part, ImagePart) for part in m.content)
        for m in messages
    )


# OpenAI's Chat Completions/Responses APIs hard-reject any tool/function
# name over 128 chars. A hallucinated name that's merely too long is
# harmless on its own turn (it just fails `ToolRegistry` resolution like any
# other unknown name) — the real danger is that it then gets stored
# verbatim in `AssistantMessage.tool_calls` and re-serialized as history on
# every later turn, so a model/gateway that degenerates into repeating its
# own bad name (see `_collapse_repeated_name` in
# `app/agent_loop_lib/tools/executor.py`) can grow it past the limit and
# get the *entire* next request rejected outright, ending the run with no
# answer at all. Truncating at ingestion — the earliest point any tool-call
# name enters PipesHub's own message state — guarantees that can't happen,
# regardless of provider or degeneration pattern.
_MAX_TOOL_CALL_NAME_LEN = 128


def _clamp_tool_call_name(name: str) -> str:
    """Keeps `name` within the provider's length cap — same hash-suffix
    scheme as `_clamp_tool_call_id` above, and for the same reason: a plain
    `name[:_MAX_TOOL_CALL_NAME_LEN]` prefix could coincidentally collide
    with a real, shorter registered tool name, turning an invalid/
    hallucinated call into a *different*, unintended tool actually
    executing instead of failing with "unknown tool". Appending a content
    hash makes that coincidence practically impossible regardless of what
    tool names happen to be registered.
    """
    if len(name) <= _MAX_TOOL_CALL_NAME_LEN:
        return name
    digest = hashlib.sha256(name.encode()).hexdigest()[:16]
    prefix_len = _MAX_TOOL_CALL_NAME_LEN - 1 - len(digest)  # 1 for the `-`
    return f"{name[:prefix_len]}-{digest}"


def convert_tool_call_from_langchain(call: dict[str, Any]) -> ToolCall:
    # Every LangChain-internal constructor for a *valid* `tool_calls` entry
    # (as opposed to `invalid_tool_calls`, see `_recover_invalid_tool_call`
    # below) guarantees a string `name`, but this still takes an untyped
    # provider dict — guard against a nonconforming integration the same
    # way the invalid-call path already does, instead of a raw `call["name"]`
    # `KeyError`/non-string crashing the whole turn.
    name = call.get("name")
    if not isinstance(name, str) or not name:
        name = "unknown_tool"
    return ToolCall(
        id=call.get("id") or "",
        name=_clamp_tool_call_name(name),
        arguments=call.get("args") or {},
    )


# A small model frequently mangles tool-call argument JSON just enough that
# LangChain's own parser gives up and routes the call into
# `AIMessage.invalid_tool_calls` instead of `.tool_calls` — most often a
# stray ```json fence around the arguments, or a trailing comma before a
# closing brace/bracket. Both are cheap, unambiguous to strip, and cover
# the overwhelming majority of "almost valid" JSON weak models produce.
_JSON_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)
_TRAILING_COMMA_RE = re.compile(r",(\s*[}\]])")


def _try_repair_json(raw: str) -> tuple[dict[str, Any] | None, str | None]:
    """Best-effort recovery for tool-call argument JSON a weak model
    mangled. Returns `(parsed_args, None)` on success, `(None, error)` on
    failure — never raises, so a caller can always fall back to the
    malformed-call sentinel path."""
    if not raw or not raw.strip():
        return {}, None

    candidates = [raw]
    defenced = _JSON_FENCE_RE.sub("", raw).strip()
    if defenced != raw:
        candidates.append(defenced)
    candidates.append(_TRAILING_COMMA_RE.sub(r"\1", candidates[-1]))

    last_error = "unknown JSON parse error"
    for candidate in candidates:
        try:
            parsed = json.loads(candidate)
        except (json.JSONDecodeError, TypeError) as exc:
            last_error = str(exc)
            continue
        if isinstance(parsed, dict):
            return parsed, None
        last_error = f"parsed JSON was not an object (got {type(parsed).__name__})"
    return None, last_error


def _recover_invalid_tool_call(call: dict[str, Any]) -> ToolCall:
    """One LangChain `invalid_tool_call` entry -> a `ToolCall`, repairing
    the raw argument string when possible (see `_try_repair_json`).

    Never dropped: even when repair fails, this still returns a `ToolCall`
    (carrying `MALFORMED_TOOL_CALL_ARGS_KEY`/`_ERROR_KEY` sentinels) rather
    than `None` — a dropped call would make the turn look exactly like a
    plain no-tool-call response, letting the model "finish" the run without
    ever having actually invoked the tool it clearly intended to call. See
    `agent/tool_loop.py::execute_tool_call`'s sentinel check for how this
    turns into a corrective error `ToolMessage` on the next turn instead.
    """
    name = _clamp_tool_call_name(call.get("name") or "unknown_tool")
    raw_args = call.get("args")
    raw_args_str = raw_args if isinstance(raw_args, str) else ("" if raw_args is None else json.dumps(raw_args))

    parsed, error = _try_repair_json(raw_args_str)
    if parsed is not None:
        return ToolCall(id=call.get("id") or "", name=name, arguments=parsed)

    parse_error = error or call.get("error") or "malformed JSON arguments"
    return ToolCall(
        id=call.get("id") or "",
        name=name,
        arguments={
            MALFORMED_TOOL_CALL_ARGS_KEY: raw_args_str,
            MALFORMED_TOOL_CALL_ERROR_KEY: str(parse_error),
        },
    )


def _is_truncated(ai_message: AIMessage) -> bool:
    metadata = ai_message.response_metadata or {}
    finish_reason = metadata.get("finish_reason") or metadata.get("stop_reason")
    if finish_reason in _TRUNCATION_FINISH_REASONS:
        return True
    incomplete_details = metadata.get("incomplete_details")
    if not isinstance(incomplete_details, dict):
        return False
    return incomplete_details.get("reason") in _TRUNCATION_INCOMPLETE_REASONS


def convert_assistant_message_from_langchain(ai_message: AIMessage) -> AssistantMessage:
    """Convert a LangChain `AIMessage` response into an agent-loop
    `AssistantMessage`, using LangChain's standardized `content_blocks`
    (text/reasoning/...) so this works uniformly across the ~18 providers
    PipesHub's `BaseChatModel` wrappers cover, rather than hand-parsing each
    provider's raw `content` shape."""
    parts: list[Part] = []
    for block in ai_message.content_blocks:
        block_type = block.get("type")
        if block_type == "text":
            text = block.get("text", "")
            if text:
                parts.append(TextPart(text=text))
        elif block_type == "reasoning":
            reasoning = block.get("reasoning", "")
            if reasoning:
                parts.append(ThinkingPart(thinking=reasoning))
        # Other block types (tool_call, image, ...) are intentionally
        # skipped here: tool calls are read from `ai_message.tool_calls`
        # below, and PipesHub's LLMs don't return image content blocks.

    tool_calls = [convert_tool_call_from_langchain(c) for c in (ai_message.tool_calls or [])]
    # `invalid_tool_calls` are calls the provider clearly intended to make
    # but whose argument JSON LangChain's own parser rejected outright —
    # recovered (or sentinel-marked) rather than silently dropped; see
    # `_recover_invalid_tool_call`.
    tool_calls += [_recover_invalid_tool_call(c) for c in (ai_message.invalid_tool_calls or [])]

    return AssistantMessage(
        content=parts,
        tool_calls=tool_calls or None,
        truncated=_is_truncated(ai_message),
    )


def token_usage_from_ai_message(ai_message: AIMessage) -> TokenUsage:
    """Best-effort `TokenUsage` extraction from `AIMessage.usage_metadata`.
    Not every provider integration populates every sub-field (or even
    `usage_metadata` itself), so every access defaults to 0 rather than
    raising — a missing usage field should never crash the turn loop."""
    usage = ai_message.usage_metadata
    if not usage:
        return TokenUsage()

    input_details = usage.get("input_token_details") or {}
    return TokenUsage(
        input_tokens=usage.get("input_tokens", 0) or 0,
        output_tokens=usage.get("output_tokens", 0) or 0,
        cache_read_tokens=input_details.get("cache_read", 0) or 0,
        cache_write_tokens=input_details.get("cache_creation", 0) or 0,
    )


# ---------------------------------------------------------------------------
# Tool schema conversion
# ---------------------------------------------------------------------------

_JSON_SCHEMA_TYPE_MAP: dict[str, Any] = {
    "string": str,
    "integer": int,
    "number": float,
    "boolean": bool,
}


# Values a `Literal[...]` accepts as type arguments. JSON Schema allows an
# `enum` member to be any value, including an object or array — those fall
# through to the declared primitive type instead.
_LITERAL_SAFE_TYPES = (str, int, bool, type(None))


def _json_schema_to_python_type(schema: dict[str, Any], model_name: str, field_name: str) -> Any:  # noqa: ANN401
    """Best-effort JSON-schema-fragment -> Python type mapping for the flat,
    hand-authored schemas agent-loop's planner/critic/intent modules pass to
    `complete_structured` (see `agent/goal.py::_GOAL_SCHEMA` for the shape:
    no `$ref`/`$defs`, at most one level of `array`/`object` nesting).
    Anything unrecognized degrades to `Any` rather than raising — a
    too-loose field type is far cheaper than failing to bind tools at all.

    Reached only from `output_schema_to_pydantic_model` — the tool-calling
    path passes `input_schema` through verbatim (see
    `convert_tool_schema_to_langchain_dict`) and never builds a model.
    """
    schema_type = schema.get("type")
    enum_values = schema.get("enum")

    if enum_values and all(isinstance(v, _LITERAL_SAFE_TYPES) for v in enum_values):
        # `Literal` keeps the declared type AND the allowed values. Mapping
        # the primitive type alone drops the enum; returning bare `Any` drops
        # both, letting a provider's structured response put an object in a
        # field declared `{"type": "string", "enum": [...]}`.
        return Literal[tuple(enum_values)]

    # `isinstance` guard, not a bare `in`: a list-valued `type` is unhashable
    # and would raise `TypeError` from the dict lookup.
    if isinstance(schema_type, str) and schema_type in _JSON_SCHEMA_TYPE_MAP:
        return _JSON_SCHEMA_TYPE_MAP[schema_type]

    if schema_type == "array":
        item_schema = schema.get("items") or {}
        item_type = _json_schema_to_python_type(item_schema, model_name, f"{field_name}_item")
        return list[item_type]

    if schema_type == "object":
        nested_name = f"{model_name}_{field_name}".title().replace("_", "")
        return _json_schema_to_pydantic_model(nested_name, schema)

    return Any


def _json_schema_to_pydantic_model(name: str, schema: dict[str, Any]) -> type[BaseModel]:
    """Dynamically build a Pydantic model from a JSON-schema `object`
    fragment, for LangChain integrations whose `with_structured_output()`
    doesn't accept a raw dict schema (see `LangChainTransport.complete_structured`'s
    docstring for when this fallback path is used)."""
    properties: dict[str, Any] = schema.get("properties", {}) or {}
    required = set(schema.get("required", []) or [])

    fields: dict[str, Any] = {}
    for field_name, field_schema in properties.items():
        python_type = _json_schema_to_python_type(field_schema, name, field_name)
        description = field_schema.get("description", "")
        if field_name in required:
            fields[field_name] = (python_type, Field(description=description))
        else:
            fields[field_name] = (python_type | None, Field(default=None, description=description))

    return create_model(name, **fields)


def output_schema_to_pydantic_model(output_schema: dict[str, Any]) -> type[BaseModel]:
    """Public entry point for `LangChainTransport.complete_structured`'s
    dynamic-model fallback."""
    return _json_schema_to_pydantic_model("StructuredOutput", output_schema)


# Meta-keywords that carry no meaning inside a function-calling `parameters`
# schema — a `$schema`/`$id` pointing at a draft URL describes the document,
# not the arguments, so no provider has any use for it.
_SCHEMA_META_KEYS_TO_STRIP = frozenset({"$schema", "$id"})


def _sanitize_tool_input_schema(schema: Any) -> Any:  # noqa: ANN401
    """Strips `$schema`/`$id` and any leftover `$ref` from a tool's JSON
    Schema before it reaches `bind_tools()`.

    `MCPToolAdapter.raw_input_schema` (`mcp_tool_adapter.py`) already inlines
    every `$ref`/`$defs` up front via `resolve_json_schema_refs`, so a `$ref`
    surviving to here should not happen — this is a defensive backstop, not
    the primary mechanism, which is why it drops the key rather than trying
    to re-resolve it, and why it recurses (a stray `$ref` at any depth is
    still a dangling pointer once `$defs` is gone).

    Deliberately NOT an allow-list like `transport/gemini.py::sanitize_schema`:
    every other JSON Schema keyword is kept. OpenAI, Anthropic, and Ollama
    accept them verbatim, and `langchain_google_genai` filters unknown
    keywords itself (`_format_json_schema_to_gapic`'s
    `_ALLOWED_SCHEMA_FIELDS_SET`, which logs and skips), so stripping here
    would only lose constraints the provider that DOES understand them wants.
    The one shape Gemini cannot survive is a list-valued `type`, and that is
    normalized upstream in `resolve_json_schema_refs` so both the native and
    LangChain Gemini arms benefit.
    """
    if isinstance(schema, list):
        return [_sanitize_tool_input_schema(v) for v in schema]
    if not isinstance(schema, dict):
        return schema
    return {
        key: (_sanitize_tool_input_schema(value) if isinstance(value, (dict, list)) else value)
        for key, value in schema.items()
        if key not in _SCHEMA_META_KEYS_TO_STRIP and key != "$ref"
    }


def convert_tool_schema_to_langchain_dict(schema: ToolSchema) -> dict[str, Any]:
    """`ToolSchema` -> the OpenAI function-calling dict shape, mirroring
    `OpenAITransport._format_tools` (`transport/openai.py:548`) exactly.

    `BaseChatModel.bind_tools()` accepts this shape across every LangChain
    chat model integration configured in this app — verified: it's called
    from exactly one place (`LangChainTransport._bind_tools`), and the only
    non-stock `BaseChatModel` subclass in the repo, `ChatTogether`
    (`app/utils/custom_chat_model.py`), extends `BaseChatOpenAI` and inherits
    its dict-handling `bind_tools` rather than overriding it.

    Replaces the previous round-trip through a dynamically-built Pydantic
    model (`_json_schema_to_pydantic_model`), which silently dropped `enum`,
    `default`, `minimum`/`maximum`, `additionalProperties`, and collapsed
    `anyOf`/`oneOf` unions to their first arm on every MCP tool schema.
    `_json_schema_to_pydantic_model` itself is kept for
    `output_schema_to_pydantic_model`, which `complete_structured` genuinely
    needs a model class for.
    """
    parameters = schema.input_schema or {"type": "object", "properties": {}}
    return {
        "type": "function",
        "function": {
            "name": schema.name,
            "description": schema.description,
            "parameters": _sanitize_tool_input_schema(parameters),
        },
    }


def convert_tool_schemas_to_langchain(
    tools: list[ToolSchema] | None,
) -> list[dict[str, Any]]:
    if not tools:
        return []
    return [convert_tool_schema_to_langchain_dict(t) for t in tools]


__all__ = [
    "convert_message_from_langchain",
    "convert_messages_from_langchain",
    "convert_message_to_langchain",
    "convert_messages_to_langchain",
    "convert_tool_call_from_langchain",
    "convert_assistant_message_from_langchain",
    "token_usage_from_ai_message",
    "output_schema_to_pydantic_model",
    "convert_tool_schema_to_langchain_dict",
    "convert_tool_schemas_to_langchain",
]
