"""Helpers for turning Jira Cloud rendered HTML into indexable blocks.

Currently used by the Jira Cloud connector (not Confluence or Jira Data Center, which
have their own HTML/media paths). It centralises the two operations that path needs:

  * find attachment ids referenced in the HTML (``<a href>`` links and ``<img>`` sources),
  * inline image attachments as base64 data URIs (for multimodal indexing).

The attachment-URL regex also matches Data Center ``/secure/attachment|thumbnail/``
shapes so the helpers stay reusable if DC migrates later:
  * Cloud: ``/rest/api/3/attachment/content/12345`` and ``.../thumbnail/12345``
  * Data Center: ``/secure/attachment/12345/name.png`` and ``/secure/thumbnail/12345/...``
"""
from collections.abc import Awaitable, Callable
from typing import Any, Optional

import re

from bs4 import BeautifulSoup  # type: ignore

# Numeric attachment id from a rendered-HTML URL, for both Cloud and Data Center.
ATTACHMENT_URL_RE = re.compile(
    r"/(?:rest/api/\d+/attachment/(?:content|thumbnail)|secure/(?:attachment|thumbnail))/(\d+)"
)

# User profile URLs generated by @mentions in Jira rendered HTML.
_USER_PROFILE_URL_RE = re.compile(
    r"/secure/ViewProfile\.jspa\b|/jira/people/",
    re.IGNORECASE,
)


def extract_attachment_ids(html: str) -> set[str]:
    """Return the attachment ids referenced by any ``<a href>`` or ``<img src>`` in ``html``.

    Works over the whole document, so links/images nested in tables or lists are included.
    """
    if not html:
        return set()
    return {match.group(1) for match in ATTACHMENT_URL_RE.finditer(html)}


async def inline_images_as_base64(
    html: str,
    attachments_by_id: dict[str, dict[str, Any]],
    is_image: Callable[[str], bool],
    fetch_base64: Callable[[dict[str, Any]], Awaitable[Optional[str]]],
) -> tuple[str, set[str]]:
    """Rewrite image-attachment ``<img>`` tags to base64 data URIs.

    - Finds every ``<img>`` anywhere in the document (tables and lists included).
    - Resolves the attachment id from ``src``; if it maps to an image attachment, fetches a
      base64 data URI via ``fetch_base64`` and rewrites ``src`` in place, then unwraps Jira's
      ``<a>`` / ``<span class="image-wrap">`` wrappers so the ``<img>`` is a direct child of
      its block element.
    - An *attachment* image that can't be inlined (oversized, fetch failed, or not actually an
      image) is replaced with its ``alt`` text, so no auth-only URL is left in the block. A
      non-attachment ``<img>`` (e.g. an externally hosted image) is left untouched.
    - Jira UI chrome images (``class="rendericon"`` / ``class="icon"``) are dropped.

    Returns ``(modified_html, inlined_attachment_ids)``.
    """
    inlined: set[str] = set()
    if not html:
        return html, inlined

    soup = BeautifulSoup(html, "html.parser")

    # find_all returns a materialised list, so mutating the tree while iterating is safe.
    for img in soup.find_all("img"):
        classes = img.get("class") or []
        if "rendericon" in classes or "icon" in classes:
            img.decompose()
            continue

        src = img.get("src", "") or ""
        alt = img.get("alt", "") or ""
        match = ATTACHMENT_URL_RE.search(src)
        att_id = match.group(1) if match else None

        data_uri: Optional[str] = None
        if att_id and att_id in attachments_by_id and is_image(att_id):
            data_uri = await fetch_base64(attachments_by_id[att_id])

        if data_uri:
            img["src"] = data_uri
            inlined.add(att_id)
            parent = img.parent
            if parent is not None and parent.name == "a":
                parent.unwrap()
                parent = img.parent
            if (
                parent is not None
                and parent.name == "span"
                and "image-wrap" in (parent.get("class") or [])
            ):
                parent.unwrap()
        elif att_id:
            # An attachment image we couldn't inline — drop the un-fetchable URL, keep the alt.
            img.replace_with(alt or "")
        # else: not an attachment URL (external/public image) — leave it as-is.

    _simplify_attachment_links(soup)
    simplify_user_mention_links(soup)

    return str(soup), inlined


def _simplify_attachment_links(soup: BeautifulSoup) -> None:
    """Replace file-attachment ``<a>`` links with just their text content.

    After image processing, ``<a>`` tags pointing to attachment URLs (e.g.
    ``/rest/api/3/attachment/content/12345``) still remain for non-image files.
    These URLs require authentication and are useless in indexed content — the
    files are already tracked as ``children_records``.  This replaces each such
    ``<a>`` with its visible text (the filename) and cleans up Jira's wrapper
    elements (``<span class="nobr">``, empty ``<sup>``).
    """
    for a_tag in soup.find_all("a"):
        href = a_tag.get("href", "") or ""
        if not ATTACHMENT_URL_RE.search(href):
            continue
        text = a_tag.get_text()
        parent = a_tag.parent
        a_tag.replace_with(text)
        if (
            parent is not None
            and parent.name == "span"
            and "nobr" in (parent.get("class") or [])
        ):
            parent.unwrap()

    for sup in soup.find_all("sup"):
        if not sup.get_text(strip=True):
            sup.decompose()


def simplify_user_mention_links(soup: BeautifulSoup) -> None:
    """Replace user-mention ``<a>`` links with ``@DisplayName``.

    Jira renders ``@mentions`` as ``<a href="/secure/ViewProfile.jspa?accountId=...">Name</a>``.
    These profile URLs require authentication and leak account IDs into indexed content.
    This replaces each such ``<a>`` with ``@Name`` plain text.
    """
    for a_tag in soup.find_all("a"):
        href = a_tag.get("href", "") or ""
        if not _USER_PROFILE_URL_RE.search(href):
            continue
        name = a_tag.get_text(strip=True)
        if not name:
            continue
        a_tag.replace_with(f"@{name}")
