apiVersion: v2
name: pipeshub-ai
description: AI-powered workflow automation and integration platform
type: application
version: 0.2.0
appVersion: "v0.3.0"
home: https://pipeshub.com
icon: https://pipeshub.com/logo.svg
sources:
  - https://github.com/pipeshub-ai/pipeshub-ai
maintainers:
  - name: PipesHub Team
    email: contact@pipeshub.com
    url: https://pipeshub.com
keywords:
  - ai
  - workflow
  - automation
  - integration
  - mongodb
  - redis
  - neo4j
annotations:
  category: AI/ML Platform
  licenses: Apache-2.0

dependencies:
  - name: mongodb
    version: 18.1.10
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: redis
    version: 24.0.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
